### ISSUE TITLE
track conversions

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/av-static-website#206]
```
As an admin
So that we can evaluate the effectiveness of money spent on our ads
I would like to know which ads are generating leads
```

we would like to know when people have arrived from adwords, whether they sign up for newsletter or contact us for more information on projects

**Comment by tansaku** [comment]
* [ ] investigate can we track someone clicking through on email link
* [ ] investigate can we track someone submitting our mailchimp form

**Comment by tansaku** [comment]
from @diraulo https://analyticsacademy.withgoogle.com/

**Comment by tansaku** [comment]
from @mtc2013 https://www.hallaminternet.com/mailto-link-analytics-tag-manager/

**Comment by tansaku** [comment]
Lara suggesting that we need more than in the above link ...  can we not track mailto links in adwords? http://www.upwordsem.com/5-steps-to-track-clicks-as-conversions-in-adwords/  lara suggesting we need form with thankyou page

**Comment by tansaku** [comment]
yeah @rmzse - keep meaning to work on this - keep failing ...

**Comment by fybwid** [comment]
@tansaku how about this: [MailChimp - enable and view click tracking](https://mailchimp.com/help/enable-and-view-click-tracking/)
