### ISSUE TITLE
Tell me more button does not scroll to 'Why us' section

### ISSUE THREAD

**Issue by arun1595** [AgileVentures/av-static-website#224]
To reproduce:

1. Go to http://nonprofits.agileventures.org/
2. Click on 'Tell me more' link(button)

It does nothing because the link's target is set to `#services` but we don't have that `id` in the page.

```
<a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
```

To fix: 

Replace the link target `services` with `why-us`

```
<a href="#why-us" class="page-scroll btn btn-xl">Tell Me More</a>
```

**Comment by tansaku** [comment]
thanks @arun1595 - fixed with https://github.com/AgileVentures/av-static-website/commit/739be41cc89223f58149d2a9f406c1bedd267257
