### ISSUE TITLE
add a deployment pipeline

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/av-static-website#3]
use either travis or semaphore or codeship to automate deploys

**Comment by joaopapereira** [comment]
Were do you want to deploy this? Heroku, GitHub?

**Comment by tansaku** [comment]
github pages - see http://showcase.agileventures.org

**Comment by tansaku** [comment]
Related blog posts:

* https://jahed.io/blog/2015/05/31/automating-deployments-to-github-pages-with-middleman-and-travis-ci/
* http://ryan.mcgeary.org/2013/12/19/continuous-integration-deployment-middleman-codeship-github-pages/
* http://jordanandree.com/travis-ci-deploy-middleman-github-pages/
