### ISSUE TITLE
Feedback - Showcase Navigation

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/av-static-website#37]
On the Showcase page when I hover over a site, the image switches to a big plus:
![image](https://cloud.githubusercontent.com/assets/1401069/16081298/cf2aedf8-3304-11e6-88e9-609aeb1e345f.png)

This sort of image usually means I am adding something - e.g. in c9.io it would mean "adding a workspace" - so what am I adding here?

When I click on a showcase site, the whole page is replaced - it seems a bit like a pop-up because I have a massive (why so big??) X in the corner but it takes up the whole screen - popups don't normally do that - and indeed it didn't "pop up", it faded in.
So is it a popup or a new page I have navigated to?

If I scroll down the page I also see a "Close Project" button - what does this do?  Does it literally close the project?  That's not what I want to do!  Or does it just close the popup?  The text is confusing as to the function of the button.

Also, I did have to scroll to see that button on some pages - this is what I see on a full screen retina Macbook Pro:
![image](https://cloud.githubusercontent.com/assets/1401069/16081614/2b87e3b6-3306-11e6-9c29-c3a5f9c5ebc1.png)

There is a huge amount of whitespace at the top, for the "title bar" I guess containing that giant X (And nothing else!) so I have to scroll to get the button which performs exactly the same function as the big X - do we need it?  And if we do need it, should I have to scroll to see it?  Again, is if this is a popup then the answer should be "No".

If you want to keep the giant X then maybe put the AV logo in the top left so at least you haven't lost the site branding?

Also, it's not very reactive/mobile friendly - when I reduce it to it's smallest I get this:
![image](https://cloud.githubusercontent.com/assets/1401069/16084201/cf505056-330f-11e6-9f83-e542cacd4566.png)

the massive X is still just as big as when on a fullscreen browser and the only thing that changes size is the screenshot of the site - the text stays exactly the same size as it always was.

**Comment by tansaku** [comment]
hmm, could change away from the "+" - wonder what icon might be better ...?

**Comment by freeranger** [comment]
Why does it need to change at all?  If the cursor changes to a pointing finger then people will know they can click on it.  
The image could pop out a little or glow or something like that if you want a bit more style...but the whole thing doesn't have to change completely to have a visual impact...

**Comment by tansaku** [comment]
changed icon - can remove later if we want
