### ISSUE TITLE
Feedback - Why Us?

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/av-static-website#38]
I'm not sure that this page is necessary in the "Showcase" site - this content is more appropriate in the main site I'd have thought - I would expect the showcase site to be all about showcasing the work.

I'm not sure who the target audience is for this page but assuming it is the non-profits themselves, in the "much lower cost" section you talk about "open API's" and "free modules".  As a non-profit, non-technical person, I have no idea what these terms mean.
Why do I care?  I care it is no/low cost, I understand about licence fees and overheads and staff costs - but this bit is just jargon.

I wonder if you actually need two pages - Why Us for non-profits and Why Us for developers?
Look at this site: http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/what-is-aurelia
In the top left you choose what sort of person you are and the content is tailored towards that audience - perhaps you need to consider that sort of approach since AV needs to attract both non-profits and developers - two wildly different audiences.

Regarding  your contact link on this page:

> TO DISCUSS YOUR SOFTWARE PROJECT NEEDS, EMAIL SALES@AGILEVENTURES.ORG

I think someone already mentioned in chat that this is a bit "shouty".  It is also clearly not aimed at developers who might want to contact you to get involved with AV, so what email address do they use?

Beyond that, the word "sales" equates in my mind to "cost" which is something a non-profit wants to minimise.  Perhaps a more "neutral" address is required which does not imply cost - many non-profits will have little or no cash to splash on websites so the cost associated words might scare them off.

**Comment by tansaku** [comment]
removed mention of sales and showcase
