### ISSUE TITLE
Feedback - Contact

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/av-static-website#39]
I click on the "Contact" menu item because I want to contact you.
This is what I see:
![image](https://cloud.githubusercontent.com/assets/1401069/16083193/010c73a8-330c-11e6-8215-6e234ade8372.png)

A couple of massive texts boxes so I can subscribe for updates!
I don't want to do that - I want to contact you.
If I look carefully, I can see an email address (which isn't even a hyperlink) at the bottom of the page.
On a "Contact" page, I would expect the contact-y bit to be front and centre.
Also the image I pasted is from a full screen retina MacBook Pro screen, but half of the contact info is cut off at the bottom of the screen - I shouldn't have to scroll to see the very information I came to this page for.

The stuff at the bottom of the page - apart from the contact info, which is what I want, the other info is a bit random almost - who we are and what we do - why is this on the "Contact" page and not, say the "about" page?  Or possibly at the bottom of every page?

You could make this whole thing smaller (it uses a lot of vertical space, doesn't take great advantage of horizontal space:
![image](https://cloud.githubusercontent.com/assets/1401069/16083602/7e61c87a-330d-11e6-9473-6e467db87d47.png)

and have it as a footer to every page on the site - certainly in a desktop browser.

Also needs a bit of work reactive website-wise:
Resizing it on my mac, I go from this:
![image](https://cloud.githubusercontent.com/assets/1401069/16083352/9d5cc97e-330c-11e6-9e10-91f02bd15915.png)

to this (a very slightly narrower window):
![image](https://cloud.githubusercontent.com/assets/1401069/16083378/b4af2ae0-330c-11e6-9a8c-01c4385472ca.png)

To this: (again just making it narrower):
![image](https://cloud.githubusercontent.com/assets/1401069/16083397/c5fba8d2-330c-11e6-88dd-386581d517ed.png)

If I scroll the page a bit to bring the content into view then I have this:
![image](https://cloud.githubusercontent.com/assets/1401069/16083468/ee3a93ee-330c-11e6-83d8-45968b661b11.png)

text boxes are right to the edge of the screen, which doesn't look great.  Keep on narrowing the window and I get this:
![image](https://cloud.githubusercontent.com/assets/1401069/16083485/073c0dfa-330d-11e6-8b5c-157fbbee98db.png)

so a bit more work needed on

**Comment by tansaku** [comment]
* [ ] hyperlink the contact email
* [ ] break the contact footer etc into it's own section with it's own navigation
* [ ] have a separate subscribe thing in the nav bar to navigate to subscribe ...
