### ISSUE TITLE
Feedback - About

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/av-static-website#40]
As with other pages, this is not about the showcase and does not belong as part of the showcase site.

This is largely a history of how AV was born, and there's nothing wrong with that - but this is also a place you might talk about us now - ie what you do, what you offer - the sort of content in fact that you have on other pages that are not "about us".
Or perhaps you need an "about us" page with all the details on what AV is about and what it does and a "how we started" or some such page.

The content talks about the "OSRA project" and "LocalSupport" and other things, but why aren't these links either to those sites themselves or in the two cases above, to the showcase for those sites?

The only link you have is to Craft Academy, which is not even part of AV itself, just someone you collaborate with.  You mention the AV premium services but don't link to them either.

Missed opportunities - the web is good at linking to other pages and sites - you should use it!

**Comment by tansaku** [comment]
could add some more links in here ...

**Comment by tansaku** [comment]
https://github.com/AgileVentures/av-static-website/commit/e4ea0f0b4c1ac5711e6d2db6fc6cdf4c1a554623 adds some more links in this section - now that this is "nonprofits" site, and not a "showcase", perhaps we are okay with about us timeline being in this section - we can open another ticket if we really want to move it
