### ISSUE TITLE
Feedback - Showcases

### ISSUE THREAD

**Issue by freeranger** [AgileVentures/av-static-website#41]
This is a typical showcase screen:
![image](https://cloud.githubusercontent.com/assets/1401069/16084041/1e8891c0-330f-11e6-910b-57d015a12862.png)

It's not very showcase-y I'm afraid.  There is a huge amount of whitespace at the top of the page with the giant X, as I have mentioned in the navigation story: https://github.com/AgileVentures/av-static-website/issues/37

There is very little text explaining what this site is or why I should be excited about it - either as a developer or as a non-profit looking for similar functionality.
Also I have to scroll the page to see all the content in some cases - which shouldn't be necessary when there is so little of it!  But more content please rather than less to make the page fit!

The use of colour is sparing but effective on the site itself, but on these showcase pages it has all but disappeared and it doesn't feel very...vibrant or exciting - sorry I can't provide more helpful descriptions.
There's no "wow" factor, they don't leap out at me.
In the example I pasted in from Snow Angels, is that really the most exciting screenshot of the app?

Consistency: The images I see on the showcase list don't appear on the showcase page for that site.
For example this:
![image](https://cloud.githubusercontent.com/assets/1401069/16084672/87b25800-3311-11e6-92d8-ccc847c531bf.png)
Which is a nice image of a vibrant looking website.  When I click on it, I get this:
![image](https://cloud.githubusercontent.com/assets/1401069/16084723/b2427730-3311-11e6-99c6-d168b46adf98.png)
and at first I don't know if I've clicked into the right link or not - I don't see that initial image again there is none of the colour or anything else about the image I clicked to suggest that I am on a related page.
Consider repeating the image the person clicked on, say top left-ish, so you know you are on the right page.
In this specific instance, consider making OSRA more prominent - as part of the title.

How about links to the actual sites themselves?  Even better than just seeing a static screenshot is being able to jump to the site to try it out - obviously not possible in a back office only site but certainly possible for the majority of AV projects.
You provide a link to the source code, which is nice for developers, but bugger all use for anyone else!
If the showcase is primarily to attract non-profits then have links relevant to them.

Dog-fooding - why isn't the main AV site listed here?  It was, after all, created by the AV community - don't you want to show that your devs are good enough to work on your own site as well as the sites of non-profits?  agileventures.org is at least one of the more colourful sites you have so even a static image of that stands out more than some of the admin back ends.

Finally, since mobile is where it's at these days, perhaps some of the mobile apps should be higher up the list of case studies?

**Comment by tansaku** [comment]
Yeah, so key problem with OSRA and SnowAngels is that they are back end office apps, so can't really have people accessing those and playing around - unless we can keep some dev versions running for fun - hmmm.

I think we do better with the lookup case study, but what we've got here is a template that's designed for showing great design and graphics, and that's not our speciality.  We want to highlight how we've worked with a client to understand their needs - so a single big image is maybe not the best - maybe we'd be better off with a big clear stakeholder diagram for each ...
