### ISSUE TITLE
Email link in the contact section flows out of the viewport

### ISSUE THREAD

**Issue by arun1595** [AgileVentures/av-static-website#46]
Since the font-size of `.footer .contact-list` div is `1.5em` and we have applied `padding-left` of `20%` to it, the email link flows out of the viewport. 

http://nonprofits.agileventures.org/#contact

**Suggested fix**: 

Reduce the font-size of `.footer .contact-list` to `1.2em`. To stay consistent, we should also reduce the font-size of `.footer .list` to `1.2em`

**Comment by tansaku** [comment]
@arun1595 cool - feel free to submit a PR
