### ISSUE TITLE
Display blog author's name at the top

### ISSUE THREAD

**Issue by arku** [AgileVentures/av-static-website#47]
Currently, we display the author name at the end of the blog. It would be better if we could display it right below the blog title.  See [here](http://nonprofits.agileventures.org/2016/09/01/how-much-sandboxing/).

Also, we should consider making the title a link pointing to the author's AV profile or personal or github profile.

**Comment by tansaku** [comment]
@arun1595 definitely agree about the second one - having the link to the profile etc. not so sure about having the author name at the top - could go either way
